version: "3.7"

services:
  chrome:
    image: selenium/standalone-chrome:3.141.59-20200409
    volumes:
      #TODO what is this for?
      - /dev/shm:/dev/shm
    ports:
      - 4444:4444
    restart: unless-stopped
